default_settings: null
behaviors:
  SimpleRunner:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
        learning_rate: 0.0003
        encoding_size: null
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  level:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1899
          value: 0.0
      name: Lesson0
      completion_criteria:
        behavior: SimpleRunner
        measure: reward
        min_lesson_length: 200
        signal_smoothing: true
        threshold: 750.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1900
          value: 1.0
      name: Lesson1
      completion_criteria:
        behavior: SimpleRunner
        measure: reward
        min_lesson_length: 200
        signal_smoothing: true
        threshold: 750.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1901
          value: 2.0
      name: Lesson2
      completion_criteria:
        behavior: SimpleRunner
        measure: reward
        min_lesson_length: 200
        signal_smoothing: true
        threshold: 750.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1902
          value: 3.0
      name: Lesson3
      completion_criteria: null
checkpoint_settings:
  run_id: SimpleRunner_004
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
